#!/bin/bash
# Um script de menu de energia simples usando rofi

OPTIONS=" Lock\n Logout\n Suspend\n Reboot\n Shutdown"

# Exibe o rofi
CHOICE=$(echo -e "$OPTIONS" | rofi -dmenu -i -p "Power Menu" -width 20 -lines 5)

# Executa a ação escolhida
case "$CHOICE" in
    " Lock")
        i3lock -c 000000 
        ;;
    " Logout")
        i3-msg exit
        ;;
    " Suspend")
        systemctl suspend
        ;;
    " Reboot")
        systemctl reboot
        ;;
    " Shutdown")
        systemctl poweroff
        ;;
esac
